// Package server exposes the Roku Direct Publisher feed, the public listings
// API, and a health endpoint.
package server

import (
	"context"
	"encoding/json"
	"log/slog"
	"net/http"
	"time"

	httpSwagger "github.com/swaggo/http-swagger"

	_ "github.com/dwellingtw/backend/docs" // swagger spec, generated by `make swagger`
	"github.com/dwellingtw/backend/internal/api"
	"github.com/dwellingtw/backend/internal/feed"
	"github.com/dwellingtw/backend/internal/property"
)

// feedSource provides the listings whose videos are ready.
type feedSource interface {
	ListReadyForFeed(ctx context.Context) ([]property.Property, error)
}

// Server serves the Roku feed.
type Server struct {
	repo         feedSource
	providerName string
	log          *slog.Logger
	now          func() time.Time
	srv          *http.Server
	mux          *http.ServeMux

	liveURL       string
	liveThumbnail string
	liveAvailable func(context.Context) bool
}

// New creates a Server bound to addr (e.g. ":8080"). publicAPI may be nil
// (e.g. in tests that only exercise the feed).
func New(addr, providerName string, repo feedSource, publicAPI *api.API, log *slog.Logger) *Server {
	s := &Server{
		repo:         repo,
		providerName: providerName,
		log:          log,
		now:          time.Now,
	}
	mux := http.NewServeMux()
	s.mux = mux
	mux.HandleFunc("GET /roku/feed.json", s.handleFeed)
	mux.HandleFunc("GET /healthz", s.handleHealth)
	mux.Handle("GET /swagger/", httpSwagger.WrapHandler)
	if publicAPI != nil {
		publicAPI.Register(mux)
	}
	s.srv = &http.Server{
		Addr:              addr,
		Handler:           mux,
		ReadHeaderTimeout: 10 * time.Second,
	}
	return s
}

// Mounter registers routes on a mux (e.g. linear.Handler).
type Mounter interface {
	Register(mux *http.ServeMux)
}

// Mount adds routes. Call before Start.
func (s *Server) Mount(m Mounter) { m.Register(s.mux) }

// SetLiveFeed adds the linear channel to the Roku feed as a live feed.
//
// thumbnail is the channel poster (LINEAR_LIVE_THUMBNAIL_URL). Roku Direct
// Publisher requires a non-empty thumbnail on every liveFeeds entry; when
// none is configured the first ready listing's first image is borrowed, and
// when there is no image either the entry is omitted rather than published
// with a thumbnail Roku rejects — or with a branding URL nobody uploaded.
//
// available reports whether the channels have anything to play; nil means
// always. A feed that advertises a stream before any clip has been segmented
// sends viewers to a 503.
func (s *Server) SetLiveFeed(u, thumbnail string, available func(context.Context) bool) {
	s.liveURL, s.liveThumbnail, s.liveAvailable = u, thumbnail, available
}

// Start runs the HTTP server until it errors or is shut down.
func (s *Server) Start() error {
	if err := s.srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		return err
	}
	return nil
}

// Shutdown gracefully stops the server.
func (s *Server) Shutdown(ctx context.Context) error {
	return s.srv.Shutdown(ctx)
}

func (s *Server) handleFeed(w http.ResponseWriter, r *http.Request) {
	props, err := s.repo.ListReadyForFeed(r.Context())
	if err != nil {
		s.log.Error("feed query failed", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	doc := feed.Build(s.providerName, props, s.now())
	s.addLiveFeed(r.Context(), &doc, props)

	w.Header().Set("Content-Type", "application/json")
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	if err := enc.Encode(doc); err != nil {
		s.log.Error("feed encode failed", "error", err)
	}
}

// addLiveFeed appends the linear channel to doc when it is configured, has
// content, and has a thumbnail to show.
func (s *Server) addLiveFeed(ctx context.Context, doc *feed.Feed, props []property.Property) {
	if s.liveURL == "" {
		return
	}
	if s.liveAvailable != nil && !s.liveAvailable(ctx) {
		s.log.Warn("roku live feed omitted: the channels have no content yet", "url", s.liveURL)
		return
	}
	thumb := s.liveThumbnail
	if thumb == "" {
		thumb = firstImage(props)
	}
	if thumb == "" {
		s.log.Warn("roku live feed omitted: no LINEAR_LIVE_THUMBNAIL_URL and no listing image to borrow", "url", s.liveURL)
		return
	}
	doc.AddLive(s.liveURL, thumb, s.now())
}

// firstImage returns the first image of the first listing that has one.
func firstImage(props []property.Property) string {
	for _, p := range props {
		if len(p.ImageURLs) > 0 && p.ImageURLs[0] != "" {
			return p.ImageURLs[0]
		}
	}
	return ""
}

func (s *Server) handleHealth(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write([]byte(`{"status":"ok"}`))
}
